
image: python:3.6

options:
  max-time: 6

pipelines:
  default:
    - parallel:
      - step:
          name: Build & Test 3.6
          image: python:3.6
          caches: &caches
            - pip
          script: &build_test
            - mkdir -p /etc/assemblyline/
            - mkdir -p /var/cache/assemblyline/
            - cp test/bitbucket/config.yml /etc/assemblyline
            - apt update
            - apt install -y build-essential libffi-dev libfuzzy-dev python3-dev
            - pip install -r al_ui/requirements.txt -r test/requirements.txt
            - PYTHONPATH=. python3 al_ui/app.py &
            - PYTHONPATH=. python3 al_ui/socketsrv.py &
            - pytest -rsx -vv
          services: &services
            - elasticsearch
            - redis
            - nginx
            - minio
      - step:
          name: Build & Test 3.7
          image: python:3.7
          caches: *caches
          script: *build_test
          services: *services
      - step:
          name: Build & Test 3.8
          image: python:3.8-rc
          caches: *caches
          script: *build_test
          services: *services

definitions:
  services:
    elasticsearch:
      image: sgaroncse/elasticsearch:7.0.0
      memory: 2048
      environment:
        ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        DISCOVERY_TYPE: "single-node"

    redis:
      image: redis
      memory: 256

    nginx:
      image: sgaroncse/nginx-ssl-bitbucket:1.15.10
      memory: 256

    minio:
      image: sgaroncse/minio
      memory: 256
      environment:
        MINIO_ACCESS_KEY: al_storage_key
        MINIO_SECRET_KEY: Ch@ngeTh!sPa33w0rd
