
image: python:3.6

options:
  max-time: 6

pipelines:
  default:
    - parallel:
      - step:
          name: Build & Test 3.6
          image: python:3.6
          caches: &caches
            - pip
          script: &build_test
            - apt update
            - apt install -y build-essential libffi-dev libfuzzy-dev python3-dev
            - mkdir -p /etc/assemblyline/
            - mkdir -p /var/cache/assemblyline/
            - mkdir -p /var/lib/assemblyline/
            - cp test/bitbucket/config.yml /etc/assemblyline
            - pip install -r test/requirements.txt
            - pip install -e .
            - python3 -m al_ui.app &
            - python3 -m al_ui.socketsrv &
            - pytest -rsx -vv
          services: &services
            - elasticsearch
            - redis
            - nginx
            - minio
      - step:
          name: Build & Test 3.7
          image: python:3.7
          caches: *caches
          script: *build_test
          services: *services
#      - step:
#          name: Build & Test 3.8
#          image: python:3.8-rc
#          caches: *caches
#          script: *build_test
#          services: *services

  tags:
    v*:
      - step:
          name: Build Package
          image: python:3.6
          script:
            - pip install wheel
            - python setup.py bdist_wheel
            - ls dist/
          artifacts:
            - dist/*
      - parallel:
        - step:
            name: Test 3.6
            image: python:3.6
            services: *services
            script: &deploy_test
              - rm -rf al_core setup.py  # Make sure we are running on the package from the prior build
              - apt update
              - apt install -y build-essential libffi-dev libfuzzy-dev python3-dev
              - pip install -f dist assemblyline-ui
              - mkdir -p /etc/assemblyline/
              - mkdir -p /var/cache/assemblyline/
              - mkdir -p /var/lib/assemblyline/
              - cp test/bitbucket/config.yml /etc/assemblyline
              - pip install -r test/requirements.txt
              - python3 -m al_ui.app &
              - python3 -m al_ui.socketsrv &
              - pytest -rsx -vv
        - step:
            name: Test 3.7
            image: python:3.7
            services: *services
            script: *deploy_test
#        - step:
#            name: Test 3.8
#            image: python:3.8-rc
#            services: *services
#            script: *deploy_test
      - step:
          name: Deploy to Test PyPI
          deployment: test-pypi
          script:
            - pip install twine
            - ls dist
            - twine upload --skip-existing --repository-url $TEST_REPOSITORY_URL dist/*
      - parallel:
        - step:
            name: Deploy to PyPI
            trigger: manual
            deployment: pypi
            script:
              - pip install twine
              - ls dist
              - twine upload dist/*
        - step:
            name: Deploy to Docker Hub
            trigger: manual
            services: [docker]
            deployment: container
            script:
              - export TAG=${BITBUCKET_TAG#v}
              - until pip install assemblyline-ui== 2>&1 | grep -q $TAG; do sleep 2; done
              - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
              - docker build --build-arg version=$TAG -t cccs/assemblyline-ui:$TAG -t cccs/assemblyline-ui:latest docker/ui
              - docker build --build-arg version=$TAG -t cccs/assemblyline-socketio:$TAG -t cccs/assemblyline-socketio:latest docker/socketio
              - docker push cccs/assemblyline-ui
              - docker push cccs/assemblyline-socketio
definitions:
  services:
    elasticsearch:
      image: sgaroncse/elasticsearch:7.1.0
      memory: 2048
      environment:
        ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        DISCOVERY_TYPE: "single-node"

    redis:
      image: redis
      memory: 256

    nginx:
      image: sgaroncse/nginx-ssl-bitbucket:1.15.10-1
      memory: 256

    minio:
      image: sgaroncse/minio
      memory: 256
      environment:
        MINIO_ACCESS_KEY: al_storage_key
        MINIO_SECRET_KEY: Ch@ngeTh!sPa33w0rd
