
image: python:3.6

options:
  max-time: 10

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - mkdir -p /etc/assemblyline/
          - mkdir -p /var/cache/assemblyline/
          - cp test/config/config.yml /etc/assemblyline
          - apt update
          - apt install -y build-essential libffi-dev libfuzzy-dev python3-dev
          - pip install -r al_ui/requirements.txt -r test/requirements.txt
          - pip install pytest-error-for-skips  # Special for the pipeline where we know none should skip
          - python3 al_ui/app.py &
          - python3 al_ui/socketsrv.py &
          - pytest -rsx -vv --error-for-skips
        services:
          - elasticsearch
          - redis
          - nginx

definitions:
  services:
    elasticsearch:
      image: sgaroncse/elasticsearch:7.0.0
      memory: 768
      environment:
        ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        DISCOVERY_TYPE: "single-node"

    redis:
      image: redis
      memory: 256

    nginx:
      image: sgaroncse/nginx-ssl-bitbucket:1.15.10
      memory: 256